---

- hosts: asa
  gather_facts: false
  connection: networ_cli
  

  tasks:
  - name: SHOW VERSION
    asa_command:
      commands:
        - show version
    register: version
 
  - debug: var=version.stdout_lines
 
