---

- hosts: all
  remote_user: colin
  become: yes
  become_method: enable
  connection: local
  gather_facts: false
  

  tasks:
  - name: show version
    asa_command:
      commands:
        - show version
    register: version
 
  - debug: var=version.stdout_lines
 
